# Этап сборки
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build-vercel

# Этап продакшен-сервера
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Настройка Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
