# Dockerfile.dev
FROM node:20-bullseye

WORKDIR /app

# Устанавливаем зависимости
COPY package.json ./
RUN npm install

# Копируем остальное
COPY . .

# Запускаем Strapi в dev режиме
EXPOSE 1337
CMD ["npm", "run", "dev"]