# Dockerfile.build
FROM node:20-alpine AS build

WORKDIR /app
COPY package.json ./
COPY . .

# Собираем Strapi
RUN npm run build

# ---- Production stage ----
FROM node:20-alpine AS prod

WORKDIR /app
COPY --from=build /app ./

EXPOSE 1337
CMD ["npm", "run", "start"]