export enum Stores {
  PRODUCTS = 'productsStore',
  RECIPES = 'recipesStore',
  PRODUCTS_CATEGORIES = 'categoryProductsStore',
  RECIPES_CATEGORIES = 'categoryRecipesStore',
  INDICES = 'indicesStore',
  DOCUMENTATION = 'documentation',
  FAQ = 'faq',
  TAGS = 'tags',
  TAXES = 'taxes',
  SETTINGS = 'settings',
  INVOICES = 'invoices',
  CREDENTIALS = 'credentials',
  CHANGES_LOG = 'changes_log',
  DELETES_STORE = 'deletes_store',
}
